export const PROJECT_CONSTANTS = {
    DEFAULT_UNIT_ID: 1,
    DEFAULT_BCRYPT_SALT_ROUNDS: 10,
    JWT_ACCESS_EXPIRES_DEFAULT: '7d',
    JWT_REFRESH_EXPIRES_DEFAULT: '30d',
    GLOBAL_API_PREFIX: 'api/v1',
    DEFAULT_PORT: 3000,
    MONGO_CONNECTED_STATE: 1,
};
